### ISSUE TITLE
Game can't read ``io_persistence_validation.gnut`` when on the packages folder

### ISSUE THREAD

**Issue by NachosChipeados** [JMM889901/peepee.TitanFramework#10]
If the mod is installed via a mod manager, the filepath to get to ``io_persistence_validation.gnut`` is too long, causing the game to not read it and crash.

![Screenshot 2024-11-28 135341](https://github.com/user-attachments/assets/63057a07-0b48-4485-9e79-f76bc01db399)

- [ x ] I am on the most recent northstar version
- [ x ] I am on the most recent titanframework version

Launcher/mod manager: Flightcore

log:

**Comment by JMM889901** [comment]
thats less than ideal

**Comment by NachosChipeados** [comment]
nevermind, was an issue on my end and i somehow didn't realize until now
